# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
# gem "minima"

# Added at 2018-07-04 14:07:41 -0400 by root:
gem "jekyll", "~> 3.8"
